// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/calc/pkg/models/shared"
	"net/http"
)

type CalculateRequest struct {
	// The operator to apply on the variables
	Operation shared.OperationType `pathParam:"style=simple,explode=false,name=operation"`
	// The LHS value
	X float64 `queryParam:"style=form,explode=true,name=x"`
	// The RHS value
	Y float64 `queryParam:"style=form,explode=true,name=y"`
}

func (o *CalculateRequest) GetOperation() shared.OperationType {
	if o == nil {
		return shared.OperationType("")
	}
	return o.Operation
}

func (o *CalculateRequest) GetX() float64 {
	if o == nil {
		return 0.0
	}
	return o.X
}

func (o *CalculateRequest) GetY() float64 {
	if o == nil {
		return 0.0
	}
	return o.Y
}

type CalculateResponse struct {
	Calculate200TextPlainNumber *string
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CalculateResponse) GetCalculate200TextPlainNumber() *string {
	if o == nil {
		return nil
	}
	return o.Calculate200TextPlainNumber
}

func (o *CalculateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CalculateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CalculateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
