// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// OperationType - Possible operators are sum, subtract, multiply, divide
type OperationType string

const (
	OperationTypeSum      OperationType = "SUM"
	OperationTypeSubtract OperationType = "SUBTRACT"
	OperationTypeMultiply OperationType = "MULTIPLY"
	OperationTypeDivide   OperationType = "DIVIDE"
)

func (e OperationType) ToPointer() *OperationType {
	return &e
}

func (e *OperationType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SUM":
		fallthrough
	case "SUBTRACT":
		fallthrough
	case "MULTIPLY":
		fallthrough
	case "DIVIDE":
		*e = OperationType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OperationType: %v", v)
	}
}
